steps:
# Build and push frontend
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/$PROJECT_ID/tax-carri-frontend'
    - '-f'
    - 'Dockerfile.frontend'
    - '--build-arg=NEXT_PUBLIC_API_URL=$_API_URL'
    - '--build-arg=NEXT_PUBLIC_SUPABASE_URL=$_SUPABASE_URL'
    - '--build-arg=NEXT_PUBLIC_SUPABASE_ANON_KEY=$_SUPABASE_ANON_KEY'
    - '.'
  id: 'build-frontend'

# Push frontend image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/tax-carri-frontend']
  id: 'push-frontend'
  waitFor: ['build-frontend']

# Build API
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/tax-carri-api', './api']
  id: 'build-api'

# Push API image
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/tax-carri-api']
  id: 'push-api'
  waitFor: ['build-api']

# Deploy frontend to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  waitFor: ['push-frontend'] # Wait for frontend image push
  args:
    - 'run'
    - 'deploy'
    - 'tax-carri-frontend'
    - '--image=gcr.io/$PROJECT_ID/tax-carri-frontend:latest'
    - '--region=asia-northeast1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    # IAM policy is set after deployment
    - '--set-env-vars=NEXT_PUBLIC_API_URL=$_API_URL,NEXT_PUBLIC_SUPABASE_URL=$_SUPABASE_URL,NEXT_PUBLIC_SUPABASE_ANON_KEY=$_SUPABASE_ANON_KEY'

# Deploy API to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  waitFor: ['push-api'] # Wait for API image push
  args:
    - 'run'
    - 'deploy'
    - 'tax-carri-api'
    - '--image=gcr.io/$PROJECT_ID/tax-carri-api:latest'
    - '--region=asia-northeast1'
    - '--platform=managed'
    - '--allow-unauthenticated'
    - '--port=8000'

options:
  substitutionOption: ALLOW_LOOSE